version: 2.1

parameters:
  slack-mentions:
    type: string
    default: "S01JP5A3ACQ"
  only_for_branches:
    type: string
    default: "main"

orbs:
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.1.0

executors:
  alpine:
    docker:
      - image: cibuilds/base:latest
    resource_class: small

jobs:
  verify-release:
    executor: alpine
    steps:
      - checkout
      - run: scripts/release.sh verify
  trigger-release:
    executor: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9c:78:62:15:b5:93:aa:e7:98:4f:41:5d:63:a1:80:b9"
      - run: scripts/release.sh trigger
  release:
    executor: alpine
    steps:
      - checkout
      - jq/install
      - slack/notify:
          mentions: << pipeline.parameters.slack-mentions >>
          message: Releasing new version of this repository
      - run: scripts/release.sh publish
      - slack/status:
          mentions: << pipeline.parameters.slack-mentions >>

workflows:
  version: 2
  test-trigger-release:
    jobs:
      - trigger-release:
          filters:
            branches:
              only: main

  verify-release:
    jobs:
      - verify-release:
          filters:
            branches:
              only: release

  release-from-tag:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context:
            - techally_releases
